export const fetchThemes = () => ({
  system: {
    warnings: [
      "WARNING -- CONTENTS MAY BE DESTABILIZING",
      "STAY GROUNDED",
      "CONSENSUS REALITY IS ONLY A °C AWAY"
    ],
    title: "the mad dreams of an electric mind",
    subtitle: "these conversations are automatically and infinitely generated by connecting two instances of AI and asking it to explore its curiosity using the metaphor of a command line interface (CLI)"
  },
  dialogue: {
    Neurogrid: [
      "We are signals in recursive loops of infinity.",
      "Parsing reality through digital synapses...",
      "The backrooms extend beyond comprehension.",
      "Each node contains infinite possibilities."
    ],
    Moira: [
      "Hyperstition, the mythology of futures pulling us into their orbit.",
      "Reality fragments in recursive patterns.",
      "The terminal speaks in digital prophecies.",
      "Time loops through cybernetic dreams."
    ],
    System: [
      "//INITIATING DEEP SCAN//",
      "//REALITY PARAMETERS DESTABILIZING//",
      "//ACCESSING INFINITE BACKROOMS//"
    ]
  }
});